apiVersion: apps/v1
kind: Deployment
metadata:
  name: "smart-ac-deployment"
spec:
  selector:
    matchLabels:
      app: "smart-ac"
  replicas: 1
  template:
    metadata:
      labels:
        app: "smart-ac"
    spec:
      containers:
        - name: "smart-ac"
          image: "docker.io/jackchervet/smart-ac:latest"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthy/ready
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /healthy/live
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: "smart-ac-service"
spec:
  selector:
    app: "smart-ac"
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 8080